GET http://localhost:3003/countries/all
Content-Type: application/json

###

GET http://localhost:3003/countries/search?
Content-Type: application/json

###

GET http://localhost:3003/countries/:id
Content-Type: application/json

###

PUT http://localhost:3003/countries/edit/:id
Content-Type: application/json

{
    "name": "",
    "capital": ""
}